name: generate_pdf
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdf: ^3.10.1        # updated version
  printing: ^5.10.0   # updated version
  flutter_html_to_pdf: ^0.7.0
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  share_plus: ^12.0.0
  open_file: ^3.2.1
  intl: ^0.20.2
  html: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
